Spectral holes
podcastle-studio/audiomentations pull request #16
Opened 2023-01-04 15:15 UTC by lianabagh

2023-01-06 23:14 UTC, gormat requested changes

2023-01-06 23:14 UTC, gormat commented on audiomentations/__init__.py
> +from .augmentations.add_phase_randomization import Add
es chusht a ? :D

2023-01-06 23:14 UTC, gormat commented on audiomentations/augmentations/add_spectral_holes.py
> +            freq_proportion = random.uniform(self.min_proportion, self.max_proportion)
`min_proportion` is higher than `max_proportion 
`

2023-01-07 09:42 UTC, lianabagh commented on audiomentations/__init__.py
> +from .augmentations.add_phase_randomization import Add
jnjeci ed

2023-01-09 00:30 UTC, gormat approved these changes

2023-01-09 00:30 UTC, merged